name: kpneumo_wgs
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # --- Base system ---
  - python=3.9
  - pandas=2.2.1
  - snakemake=7.32.4
  - sra-tools=3.0.10

  # --- QC & Trimming ---
  - fastqc=0.12.1
  - fastp=0.23.4
  - multiqc=1.19

  # --- Alignment & BAM QC ---
  - bwa=0.7.17
  - samtools=1.19
  - qualimap=2.2.2

  # --- Variant Calling & Annotation ---
  - freebayes=1.3.6
  - vcflib=1.0.3
  - snpeff=5.2
  - snpsift=5.2
  - snippy=4.6.0
  - snp-sites=2.5.1

  # --- Phylogeny ---
  - fasttree=2.1.11

  # --- Assembly & QC ---
  - spades=3.15.5
  - quast=5.2.0

  # --- AMR Profiling & Typing ---
  - abricate=1.0.1
  - rgi=6.0.3
  - ncbi-amrfinderplus=3.12.8
  - resfinder
  - kleborate
  - mlst=2.23.0
